INSERT IGNORE INTO `#__rsform_config` (`SettingName`, `SettingValue`) VALUES
('global.register.code', ''),
('global.codemirror', '0'),
('global.date_mask', 'Y-m-d H:i:s'),
('global.filtering', 'joomla'),
('global.disable_multilanguage', '0'),
('global.default_layout', 'responsive'),
('global.default_load_layout_framework', '1'),
('global.grid_show_previews', '1'),
('global.grid_show_caption', '0'),
('calculations.thousands', ','),
('calculations.decimal', '.'),
('calculations.nodecimals', '2'),
('request_timeout', '0'),
('backup.mask', 'backup-{domain}-{date}'),
('allow_unsafe', '0'),
('google.api_key', ''),
('deleteafter.interval', '10'),
('deleteafter.last_run', '0');