CREATE TABLE IF NOT EXISTS `#__vvisit_counter` 
(
	`time` INT(10) UNSIGNED NOT NULL,
	`visits` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`guests` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`bots` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`members` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	UNIQUE INDEX `time` (`time`),
	PRIMARY KEY (`time`)
)DEFAULT CHARSET=utf8;
