DROP TABLE IF EXISTS `#__jmap`;
DROP TABLE IF EXISTS `#__jmap_pingomatic`;
DROP TABLE IF EXISTS `#__jmap_menu_priorities`;
DROP TABLE IF EXISTS `#__jmap_datasets`;
DROP TABLE IF EXISTS `#__jmap_dss_relations`;
DROP TABLE IF EXISTS `#__jmap_cats_priorities`;
DROP TABLE IF EXISTS `#__jmap_google`;
DROP TABLE IF EXISTS `#__jmap_metainfo`;
DROP TABLE IF EXISTS `#__jmap_headings`;